/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults, } from "@stencil/router";
export namespace Components {
    interface AppContact {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppTechnology {
    }
    interface CmdFooter {
    }
    interface CmdHeader {
    }
    interface CmdHeading {
        "level": string;
        "weight": "normal" | "bold";
    }
    interface CmdLayoutImpact {
        "name": string;
        "title": string;
    }
    interface CmdLink {
        "href": string;
    }
    interface CmdP {
    }
    interface CmdWrapper {
    }
}
declare global {
    interface HTMLAppContactElement extends Components.AppContact, HTMLStencilElement {
    }
    var HTMLAppContactElement: {
        prototype: HTMLAppContactElement;
        new (): HTMLAppContactElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTechnologyElement extends Components.AppTechnology, HTMLStencilElement {
    }
    var HTMLAppTechnologyElement: {
        prototype: HTMLAppTechnologyElement;
        new (): HTMLAppTechnologyElement;
    };
    interface HTMLCmdFooterElement extends Components.CmdFooter, HTMLStencilElement {
    }
    var HTMLCmdFooterElement: {
        prototype: HTMLCmdFooterElement;
        new (): HTMLCmdFooterElement;
    };
    interface HTMLCmdHeaderElement extends Components.CmdHeader, HTMLStencilElement {
    }
    var HTMLCmdHeaderElement: {
        prototype: HTMLCmdHeaderElement;
        new (): HTMLCmdHeaderElement;
    };
    interface HTMLCmdHeadingElement extends Components.CmdHeading, HTMLStencilElement {
    }
    var HTMLCmdHeadingElement: {
        prototype: HTMLCmdHeadingElement;
        new (): HTMLCmdHeadingElement;
    };
    interface HTMLCmdLayoutImpactElement extends Components.CmdLayoutImpact, HTMLStencilElement {
    }
    var HTMLCmdLayoutImpactElement: {
        prototype: HTMLCmdLayoutImpactElement;
        new (): HTMLCmdLayoutImpactElement;
    };
    interface HTMLCmdLinkElement extends Components.CmdLink, HTMLStencilElement {
    }
    var HTMLCmdLinkElement: {
        prototype: HTMLCmdLinkElement;
        new (): HTMLCmdLinkElement;
    };
    interface HTMLCmdPElement extends Components.CmdP, HTMLStencilElement {
    }
    var HTMLCmdPElement: {
        prototype: HTMLCmdPElement;
        new (): HTMLCmdPElement;
    };
    interface HTMLCmdWrapperElement extends Components.CmdWrapper, HTMLStencilElement {
    }
    var HTMLCmdWrapperElement: {
        prototype: HTMLCmdWrapperElement;
        new (): HTMLCmdWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "app-contact": HTMLAppContactElement;
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-technology": HTMLAppTechnologyElement;
        "cmd-footer": HTMLCmdFooterElement;
        "cmd-header": HTMLCmdHeaderElement;
        "cmd-heading": HTMLCmdHeadingElement;
        "cmd-layout-impact": HTMLCmdLayoutImpactElement;
        "cmd-link": HTMLCmdLinkElement;
        "cmd-p": HTMLCmdPElement;
        "cmd-wrapper": HTMLCmdWrapperElement;
    }
}
declare namespace LocalJSX {
    interface AppContact {
    }
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppTechnology {
    }
    interface CmdFooter {
    }
    interface CmdHeader {
    }
    interface CmdHeading {
        "level"?: string;
        "weight"?: "normal" | "bold";
    }
    interface CmdLayoutImpact {
        "name"?: string;
        "title"?: string;
    }
    interface CmdLink {
        "href"?: string;
    }
    interface CmdP {
    }
    interface CmdWrapper {
    }
    interface IntrinsicElements {
        "app-contact": AppContact;
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-technology": AppTechnology;
        "cmd-footer": CmdFooter;
        "cmd-header": CmdHeader;
        "cmd-heading": CmdHeading;
        "cmd-layout-impact": CmdLayoutImpact;
        "cmd-link": CmdLink;
        "cmd-p": CmdP;
        "cmd-wrapper": CmdWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-contact": LocalJSX.AppContact & JSXBase.HTMLAttributes<HTMLAppContactElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-technology": LocalJSX.AppTechnology & JSXBase.HTMLAttributes<HTMLAppTechnologyElement>;
            "cmd-footer": LocalJSX.CmdFooter & JSXBase.HTMLAttributes<HTMLCmdFooterElement>;
            "cmd-header": LocalJSX.CmdHeader & JSXBase.HTMLAttributes<HTMLCmdHeaderElement>;
            "cmd-heading": LocalJSX.CmdHeading & JSXBase.HTMLAttributes<HTMLCmdHeadingElement>;
            "cmd-layout-impact": LocalJSX.CmdLayoutImpact & JSXBase.HTMLAttributes<HTMLCmdLayoutImpactElement>;
            "cmd-link": LocalJSX.CmdLink & JSXBase.HTMLAttributes<HTMLCmdLinkElement>;
            "cmd-p": LocalJSX.CmdP & JSXBase.HTMLAttributes<HTMLCmdPElement>;
            "cmd-wrapper": LocalJSX.CmdWrapper & JSXBase.HTMLAttributes<HTMLCmdWrapperElement>;
        }
    }
}
